### ISSUE TITLE
Intern Server Error when selecting 

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#114] opened 2021-08-27 14:21 UTC
![image](https://user-images.githubusercontent.com/4494906/131142211-6b8f08f3-468f-40a7-9a4d-fa59ad04ec2f.png)

**Comment by tumido** [comment] 2021-08-31 13:42
Duplicate of https://github.com/AICoE/meteor/issues/115

**Closed by tumido** 2021-08-31 13:42 UTC
