### ISSUE TITLE
Internal Server Error when selecting "open as jupyterhub" 

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/meteor#115] opened 2021-08-27 14:26 UTC
![image](https://user-images.githubusercontent.com/4494906/131142211-6b8f08f3-468f-40a7-9a4d-fa59ad04ec2f.png)

I get the above error after shutting down my jupyterhub pod a selecting "open as jupyterhub" from the meteor order page.

**Comment by 4n4nd** [comment] 2021-08-30 14:24
This was a known issue in Jupyterhub MOC/Zero env. Issue: https://github.com/operate-first/support/issues/365

**Comment by tumido** [comment] 2021-08-31 13:42
Closing as duplicate of https://github.com/operate-first/support/issues/365 

Feel free to reopen if this manifests in the devconfus cluster as well.

**Closed by tumido** 2021-08-31 13:42 UTC
Labels: kind/bug, human_intervention_required
